import { Outfit} from "next/font/google";
import "./globals.css";
import Navbar from "@/conponents/Navber";
import Footer from "@/conponents/Footer";


const OutfitFont = Outfit({
  subsets: ["latin"],
});



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${OutfitFont.className}  h-full antialiased`}
    >
      <head>
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css"
        />
      </head>
      <body >
        <Navbar></Navbar>
        <main className="max-w-7xl mx-auto px-4 md:px-0">
          {children}
        </main>
        
        <Footer></Footer>
        </body>
    </html>
  );
}
